<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'mediawiki-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'f166906c5d432d2d9541e71945b1b87e706f3012',
        'name' => 'mediawiki/core',
        'dev' => false,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v1.11.0',
            'version' => '1.11.0.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'reference' => 'ae03311f45dfe194412081526be2e003960df74b',
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '647490bbcaf7fc4891c58f47b825eb99d19c377a',
            'dev_requirement' => false,
        ),
        'cssjanus/cssjanus' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cssjanus/cssjanus',
            'aliases' => array(),
            'reference' => '93db9fb39c2f9bcf287715ae254c088b14a77799',
            'dev_requirement' => false,
        ),
        'data-values/common' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/common',
            'aliases' => array(),
            'reference' => '315bd95ef8e5c360ce8a1cf02c0eef35bbb92561',
            'dev_requirement' => false,
        ),
        'data-values/data-values' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/data-values',
            'aliases' => array(),
            'reference' => '63dee286f8bb4ae7899c2d2e8d439e7b5332cc49',
            'dev_requirement' => false,
        ),
        'data-values/geo' => array(
            'pretty_version' => '4.3.0',
            'version' => '4.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/geo',
            'aliases' => array(),
            'reference' => '58fe0a1d027fce6feddbbe97d04678c6b2e40f17',
            'dev_requirement' => false,
        ),
        'data-values/interfaces' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/interfaces',
            'aliases' => array(),
            'reference' => '244d078954bc05edf8f8c6b088e848289171c3a8',
            'dev_requirement' => false,
        ),
        'data-values/validators' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../data-values/validators',
            'aliases' => array(),
            'reference' => '83dbac2c5e9442e8fa2119c8b941ecb88156abe8',
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v6.8.2',
            'version' => '6.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'reference' => '619c78266999c6e431df9ca0f844e8f656ac145b',
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'reference' => 'abe3791d231167f14eb80d413420d1eab91163a8',
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'reference' => '0b78f89d8e0bb9e380046c31adfa40347e9f663b',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '8e7d04f1f6450fef59366c399cfad4b9383aa30d',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'dc960a912984efb74d0a90222870c72c87f10c91',
            'dev_requirement' => false,
        ),
        'jeroen-de-dauw/simple-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jeroen/file-fetcher' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher',
            'aliases' => array(),
            'reference' => '7a17d947e268e351efc42386d4454a41b07ad481',
            'dev_requirement' => false,
        ),
        'jeroen/file-fetcher-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/file-fetcher-cache',
            'aliases' => array(),
            'reference' => '048ca2f966edcb38989332d13543185e864200ba',
            'dev_requirement' => false,
        ),
        'jeroen/simple-cache' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/simple-cache',
            'aliases' => array(),
            'reference' => '159a72cf2ba7b7506495914d294d9e423700bd54',
            'dev_requirement' => false,
        ),
        'jeroen/simple-geocoder' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeroen/simple-geocoder',
            'aliases' => array(),
            'reference' => '1a9e6a6b8318d712363b53b1715aee5ce266e6b8',
            'dev_requirement' => false,
        ),
        'jmikola/geojson' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jmikola/geojson',
            'aliases' => array(),
            'reference' => '6ec3016cc0215667b7775f6ead7bd0337ad66eee',
            'dev_requirement' => false,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.11',
            'version' => '5.2.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'reference' => '2ab6744b7296ded80f8cc4f9509abbff393399aa',
            'dev_requirement' => false,
        ),
        'liuggio/statsd-php-client' => array(
            'pretty_version' => 'v1.0.18',
            'version' => '1.0.18.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../liuggio/statsd-php-client',
            'aliases' => array(),
            'reference' => 'c42e6d6687b7b2d7683186ec7f4f03351cc3dbca',
            'dev_requirement' => false,
        ),
        'mediawiki/core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'mediawiki-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'f166906c5d432d2d9541e71945b1b87e706f3012',
            'dev_requirement' => false,
        ),
        'mediawiki/data-values' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/maps' => array(
            'pretty_version' => '7.20.1',
            'version' => '7.20.1.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Maps',
            'aliases' => array(),
            'reference' => 'd3ebb2c437678dd8477910274cdbfe6b030666f7',
            'dev_requirement' => false,
        ),
        'mediawiki/mediawiki' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.35.3',
            ),
        ),
        'mediawiki/mermaid' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Mermaid',
            'aliases' => array(),
            'reference' => '9e4859bd655b35572a1a68a882692032eebb2e86',
            'dev_requirement' => false,
        ),
        'mediawiki/page-forms' => array(
            'pretty_version' => '5.2.1',
            'version' => '5.2.1.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/PageForms',
            'aliases' => array(),
            'reference' => '01a2363f7520668c1cde7d4568cb8b00da0b394b',
            'dev_requirement' => false,
        ),
        'mediawiki/parser-hooks' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mediawiki/parser-hooks',
            'aliases' => array(),
            'reference' => '45660efef737bcf33abbbb12c1ddb049c4e713fe',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-breadcrumb-links' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticBreadcrumbLinks',
            'aliases' => array(),
            'reference' => 'e30360b10f5d3004e305dbf52c3bcca8908fbdf1',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-bundle' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticBundle',
            'aliases' => array(),
            'reference' => '8d04ccec53c6c51fdaf40bebe2dd314dcb60120e',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-cite' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticCite',
            'aliases' => array(),
            'reference' => '01dc68a453e1d85146742bf7b89623e761056728',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-compound-queries' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticCompoundQueries',
            'aliases' => array(),
            'reference' => '75e8b383b20486809801432133cc9d57bd0a0306',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-extra-special-properties' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticExtraSpecialProperties',
            'aliases' => array(),
            'reference' => '01a45e484adf008f5edc23e3f499d92863e379f7',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-interlanguage-links' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticInterlanguageLinks',
            'aliases' => array(),
            'reference' => 'dd553d662aafbb8a9ef38ea271d17ad465753846',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-maps' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/semantic-media-wiki' => array(
            'pretty_version' => '3.2.3',
            'version' => '3.2.3.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticMediaWiki',
            'aliases' => array(),
            'reference' => '5619c2db49184e862eecc72375e190de0e103df7',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-mediawiki' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mediawiki/semantic-meta-tags' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticMetaTags',
            'aliases' => array(),
            'reference' => '105133e586894a8ee5446f139808fc3f9dea5171',
            'dev_requirement' => false,
        ),
        'mediawiki/semantic-result-formats' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/SemanticResultFormats',
            'aliases' => array(),
            'reference' => 'ecbf369424ae5cd59315a4dca24f50d3af70702a',
            'dev_requirement' => false,
        ),
        'mediawiki/validator' => array(
            'pretty_version' => '2.2.3',
            'version' => '2.2.3.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/Validator',
            'aliases' => array(),
            'reference' => '944421640b3b34273b3722fbfd155550f1c7a8c6',
            'dev_requirement' => false,
        ),
        'nicmart/tree' => array(
            'pretty_version' => 'v0.2.7',
            'version' => '0.2.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nicmart/tree',
            'aliases' => array(),
            'reference' => '0616b54bb49938e1a816141d7943db48ebf76938',
            'dev_requirement' => false,
        ),
        'onoi/blob-store' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/blob-store',
            'aliases' => array(),
            'reference' => 'c3e1f15214977e904fc0e91e0480175a464977ce',
            'dev_requirement' => false,
        ),
        'onoi/cache' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/cache',
            'aliases' => array(),
            'reference' => 'ecc999186aab7c8db411aedd892b2e5fe5a0b422',
            'dev_requirement' => false,
        ),
        'onoi/callback-container' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/callback-container',
            'aliases' => array(),
            'reference' => 'cf2f4dda1b2479bc786985fdb5554af528d03e52',
            'dev_requirement' => false,
        ),
        'onoi/event-dispatcher' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/event-dispatcher',
            'aliases' => array(),
            'reference' => '2af64e3997fc59b6d1e1f8f77e65fd6311c37109',
            'dev_requirement' => false,
        ),
        'onoi/http-request' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/http-request',
            'aliases' => array(),
            'reference' => 'a7cf33bae82cffe570086fc06d6617e802c0cc74',
            'dev_requirement' => false,
        ),
        'onoi/message-reporter' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/message-reporter',
            'aliases' => array(),
            'reference' => 'ead8ef8f2868ccee6881e471295ebbaf8428c96c',
            'dev_requirement' => false,
        ),
        'onoi/remi' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/remi',
            'aliases' => array(),
            'reference' => '48898ecd1387656f6decc5bb1e38b4ecbdde5e4a',
            'dev_requirement' => false,
        ),
        'onoi/shared-resources' => array(
            'pretty_version' => '0.4.3',
            'version' => '0.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/shared-resources',
            'aliases' => array(),
            'reference' => '322273a7462eb0c15305dde9207138f00a387080',
            'dev_requirement' => false,
        ),
        'onoi/tesa' => array(
            'pretty_version' => '0.1.0',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../onoi/tesa',
            'aliases' => array(),
            'reference' => 'c8a07ca8738cf6d644e83d10ba2cb1ef93dffa7d',
            'dev_requirement' => false,
        ),
        'oojs/oojs-ui' => array(
            'pretty_version' => 'v0.39.3',
            'version' => '0.39.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oojs/oojs-ui',
            'aliases' => array(),
            'reference' => '517e59fe02a6857c35220094b8ece47800a7344e',
            'dev_requirement' => false,
        ),
        'param-processor/param-processor' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../param-processor/param-processor',
            'aliases' => array(),
            'reference' => '0850dc2af72d31b8f645e0f87a44ff4b68583a64',
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'reference' => '9609ed5e42ac5b221dfd9af85de005c59d418ee7',
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.8',
            'version' => '1.10.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'reference' => '094b39784aa02cef1a1e267a6fdfae0c42b8f2ac',
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'reference' => 'ee0e156ab94b37ac7ad10623a4a62f10a2a2d421',
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'reference' => 'bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09',
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.11',
            'version' => '1.10.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'reference' => '68d0d32ada737153b7e93b8d3c710ebe70ac867d',
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'dev_requirement' => false,
        ),
        'pleonasm/bloom-filter' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pleonasm/bloom-filter',
            'aliases' => array(),
            'reference' => '4a3292c9f83a778c44271bf4e4f6be1204b87f7b',
            'dev_requirement' => false,
        ),
        'professional-wiki/modern-timeline' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'mediawiki-extension',
            'install_path' => __DIR__ . '/../../extensions/ModernTimeline',
            'aliases' => array(),
            'reference' => '7d71884a72fcb9c476fdbca915555ca914e227b8',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.8.0',
            'version' => '2.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => 'f3cff96a19736714524ca0dd1d4130de73dbbbc4',
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.11',
            ),
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'reference' => '9ad6ce79c342fbd44df10ea95511a1b24dee5b57',
            'dev_requirement' => false,
        ),
        'serialization/serialization' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serialization/serialization',
            'aliases' => array(),
            'reference' => '6fa293415e2b70c30c1e673d8bcd04d27dc15e44',
            'dev_requirement' => false,
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'da3d9da2ce0026771f5fe64cb332158f1bd2bc33',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.99',
            ),
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '1100343ed1a92e3a38f9ae122fc0eb21602547be',
            'dev_requirement' => false,
        ),
        'wikimedia/assert' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/assert',
            'aliases' => array(),
            'reference' => 'd8e97f15b8f3d3799899e3d56452d34511be5764',
            'dev_requirement' => false,
        ),
        'wikimedia/at-ease' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/at-ease',
            'aliases' => array(),
            'reference' => '013ac61929797839c80a111a3f1a4710d8248e7a',
            'dev_requirement' => false,
        ),
        'wikimedia/base-convert' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/base-convert',
            'aliases' => array(),
            'reference' => '449f0d0237cf1e0e71faec90680c88d4af6e711d',
            'dev_requirement' => false,
        ),
        'wikimedia/cdb' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cdb',
            'aliases' => array(),
            'reference' => 'd49d96232f045311dc1f21bf0d7e40adf82a1f1d',
            'dev_requirement' => false,
        ),
        'wikimedia/cldr-plural-rule-parser' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/cldr-plural-rule-parser',
            'aliases' => array(),
            'reference' => '2b623a411b1a8efa4363e9fda9da496ab83a5d69',
            'dev_requirement' => false,
        ),
        'wikimedia/common-passwords' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/common-passwords',
            'aliases' => array(),
            'reference' => 'b9db612730d427a55e28f4a9b143b87fd72173e0',
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'dev_requirement' => false,
        ),
        'wikimedia/html-formatter' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/html-formatter',
            'aliases' => array(),
            'reference' => 'd6241e74d8091cf1fad91a764da5e1ba5f46e785',
            'dev_requirement' => false,
        ),
        'wikimedia/ip-set' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-set',
            'aliases' => array(),
            'reference' => 'f84555041a405f0ea51c64a0c7fb5fac36e99b84',
            'dev_requirement' => false,
        ),
        'wikimedia/ip-utils' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/ip-utils',
            'aliases' => array(),
            'reference' => 'c505b99c0dfab12254d64a5e064bddd13cf066ad',
            'dev_requirement' => false,
        ),
        'wikimedia/less.php' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/less.php',
            'aliases' => array(),
            'reference' => 'a486d78b9bd16b72f237fc6093aa56d69ce8bd13',
            'dev_requirement' => false,
        ),
        'wikimedia/object-factory' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/object-factory',
            'aliases' => array(),
            'reference' => '863aee60c8f9d964870b1a119d5d9e904233e1aa',
            'dev_requirement' => false,
        ),
        'wikimedia/parsoid' => array(
            'pretty_version' => 'v0.12.2',
            'version' => '0.12.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/parsoid',
            'aliases' => array(),
            'reference' => '15169a678f9f468ff6465035a32f28e8ec82003f',
            'dev_requirement' => false,
        ),
        'wikimedia/password-blacklist' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^0.1.4',
            ),
        ),
        'wikimedia/php-session-serializer' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/php-session-serializer',
            'aliases' => array(),
            'reference' => '9382814e701c94358ae02f3260b7ac4951385d83',
            'dev_requirement' => false,
        ),
        'wikimedia/purtle' => array(
            'pretty_version' => 'v1.0.7',
            'version' => '1.0.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/purtle',
            'aliases' => array(),
            'reference' => '569064c065caae036cd5a685574b6f96f05cfe33',
            'dev_requirement' => false,
        ),
        'wikimedia/relpath' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/relpath',
            'aliases' => array(),
            'reference' => '35e701ff16abf461bb8676a9d9177f86fa0b2c94',
            'dev_requirement' => false,
        ),
        'wikimedia/remex-html' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/remex-html',
            'aliases' => array(),
            'reference' => '7792461b0605b1fcd4bba47bf54cdc64790edb48',
            'dev_requirement' => false,
        ),
        'wikimedia/running-stat' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/running-stat',
            'aliases' => array(),
            'reference' => '60eebada7cc64b7073d90e7d4bab00efaafa0ba9',
            'dev_requirement' => false,
        ),
        'wikimedia/scoped-callback' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/scoped-callback',
            'aliases' => array(),
            'reference' => '0a480d9a9772634697c77598726cf24606597bd0',
            'dev_requirement' => false,
        ),
        'wikimedia/services' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/services',
            'aliases' => array(),
            'reference' => '5ef69a8a8b0d2ea115d08469bdab468f58fac820',
            'dev_requirement' => false,
        ),
        'wikimedia/textcat' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/textcat',
            'aliases' => array(),
            'reference' => '4f13aed2b32382c9d2fe9dc8b3e3fbb26ea4a2a9',
            'dev_requirement' => false,
        ),
        'wikimedia/timestamp' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/timestamp',
            'aliases' => array(),
            'reference' => '42ce5586d2189826e28ebcf4cedc96226b6d77e2',
            'dev_requirement' => false,
        ),
        'wikimedia/utfnormal' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/utfnormal',
            'aliases' => array(),
            'reference' => 'ec1ec7ce9e25cd275c532afd30bb6092a7633990',
            'dev_requirement' => false,
        ),
        'wikimedia/wait-condition-loop' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wait-condition-loop',
            'aliases' => array(),
            'reference' => '0321b8ca6a0f701f96e04e5e8e6d3e244ab05338',
            'dev_requirement' => false,
        ),
        'wikimedia/wikipeg' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wikipeg',
            'aliases' => array(),
            'reference' => '9a92384ae11e1a3b7ecfe0feef1809b1af73889b',
            'dev_requirement' => false,
        ),
        'wikimedia/wrappedstring' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/wrappedstring',
            'aliases' => array(),
            'reference' => '11b01a2286fd377cb15c2f5561e10f56d58f37a9',
            'dev_requirement' => false,
        ),
        'wikimedia/xmp-reader' => array(
            'pretty_version' => '0.7.0',
            'version' => '0.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/xmp-reader',
            'aliases' => array(),
            'reference' => '4b8ab8ea23cc2ccf2530738081cb4e146d55b86b',
            'dev_requirement' => false,
        ),
        'wikimedia/zest-css' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/zest-css',
            'aliases' => array(),
            'reference' => 'bc3346fcf2a93f02a8a6697d98c305c14ef1869f',
            'dev_requirement' => false,
        ),
        'willdurand/geocoder' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/geocoder',
            'aliases' => array(),
            'reference' => '3e86f5b10ab0cef1cf03f979fe8e34b6476daff0',
            'dev_requirement' => false,
        ),
        'zordius/lightncandy' => array(
            'pretty_version' => 'v1.2.5',
            'version' => '1.2.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zordius/lightncandy',
            'aliases' => array(),
            'reference' => '37aa381e0f27d411a630062070c7a5a2174c62e7',
            'dev_requirement' => false,
        ),
    ),
);
